version: '3.9'

services:
  old_mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: old_mysql
      MYSQL_USER: phper
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - old_mysql_data:/var/lib/mysql
      - ./docker/old_mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always

  new_mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: new_mysql
      MYSQL_USER: phper
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - new_mysql_data:/var/lib/mysql
      - ./docker/new_mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always

volumes:
  old_mysql_data:
  new_mysql_data:
